### ISSUE TITLE
java.lang.RuntimeException: Failed to load native library

### ISSUE THREAD

**Issue by nabievnurlan7** [OfficeDev/skype-android-app-sdk-samples#15]
Hi. My name is Nurlan. Your Healthcare app builds and works(Connection establishes without problems) fine. 

Then I took all classes and layots and other settings from your Healthcare app and put them into my own project. My project compiles and builds without errors. 

But! When i try to start conversation my app crashes in SkypeCall.java with error message:
"
Caused by: java.lang.RuntimeException: Failed to load native library
at com.microsoft.office.sfb.appsdk.Application.LoadNativeLibrary(Application.java:98)
at com.microsoft.office.sfb.appsdk.Application.initialize(Application.java:63)
at com.microsoft.office.sfb.appsdk.Application.getInstance(Application.java:112)
at kz.altyn.portalmobile.skype.SkypeCall.onCreate(SkypeCall.java:68)
"

at this part of the code
"
68:        mConversation = startToJoinMeeting();
69:        mConversation.addOnPropertyChangedCallback(new ConversationPropertyChangeListener());
"

Thank you for your help and God bless you!

**Comment by dskoneczny** [comment]
I added this libraries to my project manually:
http://www.awesomescreenshot.com/image/1758782/54bcd754385e4ec35415e13c098eb266
You can find this libraries in libucmp.aar file (change that file to *.zip)

**Comment by nabievnurlan7** [comment]
@dskoneczny Doesnt work. =(
I made jniLib in app/main/src. Then I put there *so files with armeabi folder. But nothing changed. Same error.
Should I do anything else except making jniLib and putting *so files there? For example: Delete "libucmp" from project build?...
Thanx a lot

**Comment by dskoneczny** [comment]
@nabievnurlan7 
Maybe something like this? 
https://www.dropbox.com/s/e8gh3heu58uc05h/Screenshot%202016-10-26%2014.12.10.png?dl=0
And paste all files (*.so) in every folder
But it's only a walkaround

**Comment by rahulyaa** [comment]
Hi,

Please dont crack open the aar and manually copy them. You will face a lot more issues if you try to this manually.

Easiest is to follow the gradle setup exactly as the HealthCare / SfbDemo sample apps:

The following steps should resolve this:
1. Copy the dependencies (aar and jar) from the SDK in your libs folder

2. Add a flatDirs section as shown here:
skype-android-app-sdk-samples/HealthcareApp/build.gradle
        flatDir {
            dirs "../app/libs"
        }

3. Add the dependencies as shown in this file:
skype-android-app-sdk-samples/HealthcareApp/app/build.gradle

    compile(name: "libucmp", ext: 'aar')
    compile(name: "platform", ext: 'aar')
    compile(name: "SkypeForBusiness", ext: 'aar')
    compile(name: "TelemetryService", ext: 'aar')
    compile(name: "ucmp-enums", ext: 'aar')
    compile(name: "TelemetryClient2", ext: 'aar')
    compile(name: "injector", ext: 'aar')
    compile(name: "android-database-sqlcipher", ext: 'aar')

This should solve the problem for you.

**Comment by nabievnurlan7** [comment]
@rahulyaa @dskoneczny I did as you said but nothing changed =(
Below is part of my build.gradle file. Thanx again

> apply plugin: 'com.android.application'
> 
> repositories
>         {
>             maven {
>                 url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
>             }
>             flatDir {
>                 dirs "../app/libs/native-libs"
>             }
>         }
> 
> android {
>     signingConfigs {
>     }
>     compileSdkVersion 23
>     buildToolsVersion '23.0.3'
>     // Change environment before building
>     def environment = 0;
> 
>     defaultConfig
>             {
>                 applicationId "kz.altyn.portalmobile"
>                 minSdkVersion 19
>                 targetSdkVersion 21
>                 multiDexEnabled true
>                 // Change version before building
>                 versionCode 25
>                 versionName "8.0.1.4"
>                 buildConfigField("int", "ENVIRONMENT", "$environment")
>             }
> 
>     dexOptions {
>         incremental true
>         javaMaxHeapSize "4g"
>         preDexLibraries=false
>         jumboMode = true
>     }
> 
>     buildTypes {
>         release {
>             minifyEnabled true
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
>         debug {
>             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
>         }
> 
>         applicationVariants.all { variant ->
>             variant.outputs.each { output ->
>                 if (environment == 0) {
>                     output.outputFile = file("$project.buildDir/apk/Altyn_Test_" + defaultConfig.versionName + ".apk")    // Test
>                 } else if (environment == 1) {
>                     output.outputFile = file("$project.buildDir/apk/Altyn_Dev_" + defaultConfig.versionName + ".apk")     // Dev
>                 } else if (environment == 2) {
>                     output.outputFile = file("$project.buildDir/apk/Altyn_Release_" + defaultConfig.versionName + ".apk") // Release
> //                    output.outputFile = file("$project.buildDir/apk/mobile-bank-prod.apk")   // Release
>                 } else if (environment == 3) {
>                     output.outputFile = file("$project.buildDir/apk/Altyn_Demo_" + defaultConfig.versionName + ".apk")    // Demo
>                 }
>             }
>         }
>     }
>     lintOptions {
>         abortOnError false
>     }
>     compileOptions {
>         sourceCompatibility JavaVersion.VERSION_1_7
>         targetCompatibility JavaVersion.VERSION_1_7
>     }
>     useLibrary 'org.apache.http.legacy'
>     productFlavors {
>     }
>     packagingOptions {
>         exclude 'META-INF/DEPENDENCIES'
>         exclude 'META-INF/NOTICE'
>         exclude 'META-INF/LICENSE'
>         exclude 'META-INF/LICENSE.txt'
>         exclude 'META-INF/NOTICE.txt'
>     }
> }
> 
> task nativeLibsToJar(type: Jar, description: 'create a jar archive of the native libs') {
>     destinationDir file("libs/native-libs")
>     baseName 'native-libs'
>     from fileTree(dir: 'libs', include: '**/*.so')
>     into 'lib/'
> }
> 
> dependencies {
>     compile fileTree(dir: 'libs', include: ['*.jar'])
>     //compile 'com.android.support:multidex:1.0.0'
> 
>     //compile 'com.google.guava:guava:18.0'
>     compile 'com.android.support:appcompat-v7:23.1.0'
>     compile 'com.android.support:design:23.1.0'
>     compile 'com.android.support:support-v4:23.0.+'
>     compile 'com.android.support:appcompat-v7:22.0.0'
>     compile 'com.android.support:design:22.2.1'
>     compile 'com.android.support:support-v4:23.2.1'
>     compile 'de.hdodenhof:circleimageview:1.2.1'
>     compile('org.apache.httpcomponents:httpmime:4.3.+') {
>         exclude module: "httpclient"
>     }
>     compile('org.apache.httpcomponents:httpcore:4.3.+') {
>         exclude module: "httpclient"
>     }
>     compile 'com.google.code.gson:gson:2.4'
>     compile 'org.xwalk:xwalk_core_library:18.48.477.13'
>     compile project(':iDMMobileSDK')
>     compile project(':backbasecxp-1.2.0')
>     compile project(':apprtc')
>     compile project(':card.io-5.1.1')
>     compile project(':tumarlicenselibrary')
>     compile 'com.android.support:support-v4:24.0.0'
>     compile 'com.jakewharton:butterknife:8.4.0'
>     compile 'com.squareup.retrofit:retrofit:1.9.0'
>     compile project(':annotations-1.0')
>     compile project(':injector')
>     compile project(':SkypeForBusiness')
>     compile project(':TelemetryClient2')
>     compile project(':TelemetryService')
>     compile project(':ucmp-enums')
>     compile project(':platform')
>     compile project(':libucmp')
>     provided('com.squareup.dagger:dagger-compiler:1.2.2') {
>         exclude group: 'com.google.guava'
>     }
> }

**Comment by rahulyaa** [comment]
No... please follow the exact way that is provided in the sample app.
Please check that your path is expanding correctly in the directory where you have saved the aar files for the sdk.

Also, annotations-1.0 should be present in the libs folder. I have seen issues where is does not pick up from another dir.

Also use compile(name: "libucmp", ext: 'aar') instead of compile project ...

**Comment by nabievnurlan7** [comment]
@dskoneczny @rahulyaa I did as you said. I put all commands and dependecies to gradlefiles. But, still doesnt work =/ App crashes

Any ideas guys? And thanx again

**Comment by rahulyaa** [comment]
If you are still seeing the same crash, it means that the flatdirs is not pointing to the right location.
Please make sure flatdirs is added in the top level build.gradle file.
Our project gradle should only add dependencies.

**Comment by nabievnurlan7** [comment]
@rahulyaa I checked up my project.gradle and build.gradle files. flatDirs added in the top level of build.gradle.
But nothing happens. Same error

May I show my project.gradle and build .gradle files?

**Comment by rahulyaa** [comment]
Sure.
Please also make sure that the path you are specifying in flatdir is resolving correctly

**Comment by nabievnurlan7** [comment]
@rahulyaa Can you explain me one thing?... :
When i am trying build app with params in gradle like "compile(name: "libucmp", ext: 'aar')" gradle cannot build app and shows error like:
"Error:Failed to resolve: :libucmp:"
Can explain me how to fix this? And what I gotta do to put this libs(*.aar files) into my "libs" folder? 
Thank you so much!

**Comment by nabievnurlan7** [comment]
@rahulyaa ??

**Comment by rahulyaa** [comment]
If you are hitting this
>> When i am trying build app with params in gradle like "compile(name: "libucmp", ext: 'aar')" gradle cannot build app and shows error like:
"Error:Failed to resolve: :libucmp:"

It means that your flatdir path is not resolving correctly.

Can you please print it out and check if the path is indeed pointing to the right location.

**Comment by tharoldD** [comment]
@nabievnurlan7 did you ever manage to get this fixed. I'm having the same issue and I have gone through all the recommended steps by @rahulyaa but to no avail.

**Comment by nabievnurlan7** [comment]
@tharoldD Nope! Same errors.

**Comment by nabievnurlan7** [comment]
@rahulyaa @tharoldD @dskoneczny

Hi, Rahulyaa! =)

**Question1:** "Can you please print it out and check if the path is indeed pointing to the right location." . Excuse me, =) can you explain how can I do that?

**Question2:** Can you have look at my gradle files?

**=======================================
1. This is my projects gradle file:**

` apply plugin: 'application'
def SDKROOT = ".."

buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven {url 'https://oss.sonatype.org/content/repositories/snapshots/'}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.3'
    }
}

allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
        flatDir {
            dirs "${SDKROOT}/mobile-bank/libs"
        }
    }
}

task clean(type: Delete) {
     delete rootProject.buildDir
    }`


**=======================================
2. And this is my build.gradle**
`
apply plugin: 'com.android.application'

repositories
        {
            maven {
                url 'https://download.01.org/crosswalk/releases/crosswalk/android/maven2'
            }
        }


dependencies {
    testCompile 'junit:junit:4.12'
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':annotations-1.0')
    compile project(':injector')
    compile project(':SkypeForBusiness')
    compile project(':TelemetryClient2')
    compile project(':TelemetryService')
    compile project(':ucmp-enums')
    compile project(':platform')
    compile project(':libucmp')
    provided('com.squareup.dagger:dagger-compiler:1.2.2') {
        exclude group: 'com.google.guava'

    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile 'com.android.support:support-v4:23.0.+'
    compile 'com.android.support:appcompat-v7:22.0.0'
    compile 'com.android.support:design:22.2.1'
    compile 'com.android.support:support-v4:23.2.1'
    compile 'de.hdodenhof:circleimageview:1.2.1'
    compile('org.apache.httpcomponents:httpmime:4.3.+') {
        exclude module: "httpclient"
    }
    compile('org.apache.httpcomponents:httpcore:4.3.+') {
        exclude module: "httpclient"
    }
    compile 'com.google.code.gson:gson:2.4'
    compile 'org.xwalk:xwalk_core_library:18.48.477.13'
    compile project(':iDMMobileSDK')
    compile project(':backbasecxp-1.2.0')
    compile project(':apprtc')
    compile project(':card.io-5.1.1')
    compile project(':tumarlicenselibrary')
    compile 'com.android.support:support-v4:24.0.0'
    compile 'com.jakewharton:butterknife:8.4.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    }
}

android {
    signingConfigs {
    }
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    def environment = 0;

    defaultConfig
            {
                applicationId "com.bank.portalmobile"
                minSdkVersion 19
                targetSdkVersion 21
                multiDexEnabled true
                versionCode 25
                versionName "8.0.1.4"
                buildConfigField("int", "ENVIRONMENT", "$environment")
            }

    dexOptions {
        incremental true
        javaMaxHeapSize "4g"
        preDexLibraries=true
        jumboMode = true
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        applicationVariants {
            minifyEnabled false
        }
    }
    lintOptions {
        abortOnError false
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
    useLibrary 'org.apache.http.legacy'
    productFlavors {
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
    }
}
`

Thank you very much!

**Comment by rahulyaa** [comment]
Try this

flatDir {
            dirs "../mobile-bank/libs"
            def dir     = file("../sfbdemo/libs").absolutePath
            println("Path " + dir)
        }

When you compile the project, this should print out if the path is resolving correctly.

Also ensure all the appsdk binaries are in the mobile-bank/libs dir.

**Comment by tharoldD** [comment]
@rahulyaa can you maybe help me to understand one thing. How come the sample apps can load the native libraries without any issues, but I'm struggling to get my app to load the same libraries even after following all your instructions to the letter. Could there be some important step that was not highlighted in the documentation(Getting started guide)???

**Comment by qiuxiaoj** [comment]
The jni lib in `libucmp` not contain x86_64 version，where am i download it? 
Thank you for your help!

**Comment by rahulyaa** [comment]
@tharoldD 
I would surely like to fix it if anything is missing.
There is no magic to this. 

1. All .jar files should be placed in the libs folder
2. You can place .aar files at any location (Just make sure that you specify the path correctly in flatdir as explained above) 
For convenience I have kept all of them in libs folder in the GuestMeetingJoin demo.
Best to follow the gradle file in the demo project.

**Comment by rahulyaa** [comment]
@qiuxiaoj Yes, we are not supporting x86_64 at this time. What is your use case? Are you trying this on an emulator?

**Comment by qiuxiaoj** [comment]
@rahulyaa Oh no.I am running on Mi4c。Thank you!

**Comment by tharoldD** [comment]
@rahulyaa could you maybe define what your setup is like so we can rule that out as a factor.

Personally I have tested on two machines.

**A MacBook** _running macOS Sierra_

and a

**PC** _running Ubuntu 16.04_


both with Android Studio 2.2 and Android SDK 25

Also... Is NDK a requirement for my project, to be able to use the sdk?

**Comment by nabievnurlan7** [comment]
@rahulyaa I did as you said and below is gradlelog:
`Path /home/lupus/AndroidStudioProjects/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
Path /home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs
`

Also I did `compile(name: "libucmp", ext: 'aar')`
But nothing changed. Same error `Error:Failed to resolve: :libucmp:`

**Comment by nabievnurlan7** [comment]
@rahulyaa  Is there any other ways to do this step 
"1. Copy the contents of the AppSDKAndroid folder into your project: Copy from your App SDK download folder into the libs folder of your project module." [Link](https://msdn.microsoft.com/en-us/skype/appsdk/gettingstarted) 
than doing "File - Project Structure - New module - Import JAR/AAR package"?
Because i added all libs in "Project Structure"

**Comment by NikhilBansal21** [comment]
@rahulyaa hello  i am also facing same problem my guest meeting app crashes with the same error earlier i fixed the problem somehow but now i am not able to resolve this issue i tried adding annotations.jar to compile by going through Project structure. I also had problem integrating it in an independant application but that too was resolved but now my guest meeting sample app is showing same error and now it is not solving . I am sending you the logcat . ill hope you can help me out

**Comment by NikhilBansal21** [comment]
Process: com.microsoft.office.sfb.sfbdemo, PID: 6226
                                                                                java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.office.sfb.sfbdemo/com.microsoft.office.sfb.sfbdemo.MainActivity}: java.lang.RuntimeException: Failed to load native library
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2198)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247)
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:139)
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                    at android.os.Looper.loop(Looper.java:136)
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5028)
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788)
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604)
                                                                                    at dalvik.system.NativeStart.main(Native Method)
                                                                                 Caused by: java.lang.RuntimeException: Failed to load native library
                                                                                    at com.microsoft.office.sfb.appsdk.Application.LoadNativeLibrary(Application.java:99)
                                                                                    at com.microsoft.office.sfb.appsdk.Application.initialize(Application.java:63)
                                                                                    at com.microsoft.office.sfb.appsdk.Application.getInstance(Application.java:113)
                                                                                    at com.microsoft.office.sfb.sfbdemo.MainActivity.onCreate(MainActivity.java:55)
                                                                                    at android.app.Activity.performCreate(Activity.java:5238)
                                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
                                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2162)
                                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2247) 
                                                                                    at android.app.ActivityThread.access$800(ActivityThread.java:139) 
                                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1210) 
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                    at android.os.Looper.loop(Looper.java:136) 
                                                                                    at android.app.ActivityThread.main(ActivityThread.java:5028) 
                                                                                    at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                    at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:788) 
                                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:604) 
                                                                                    at dalvik.system.NativeStart.main(Native Method)

**Comment by nabievnurlan7** [comment]
@rahulyaa ? =)

**Comment by nabievnurlan7** [comment]
@rahulyaa Hi. Still doesnt work. I transfered all my classes and libs to Healthcare app. But same error appears!

Can you tell me: can I use your Skype WEB SDK in my android app? Will it work properly??

**Comment by rahulyaa** [comment]
@nabievnurlan7 This isnt a problem with the SDK. Multiple people have used this. this is an issue with your configuration of the project.  But, definitely want to help you resolve this.

Lets get some things out of the way:
From your path output, there are two folders that are libs:
/home/lupus/AndroidStudioProjects/mobile-bank/libs 
/home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs 

Are these the right paths?

For the guest meeting join demo and the health care app, the AAR's arent added to the project through Android Studio. I added them by manually creating a libs folder.

For GuestMeetingJoin sample, the libs folder is created here:

skype-android-app-sdk-samples/GuestMeetingJoin/sfbdemo/libs (This folder is created manually and the files from the SDK are copied in this folder)

Similarly for the HealthCare app, the libs folder is created at this location:
skype-android-app-sdk-samples/HealthcareApp/app/libs

The libs folder is right next to the src folder.

Next, add the flatdirs and dependencies in the build.gradle as mentioned above.

**Comment by rahulyaa** [comment]
@tharoldD Building the SDK should work on both Mac and Windows

Android Studio 2.2
Gradle should be 2.1.3
TARGET_SDK_VERSION is 22

The SDK internally uses the NDK. Should not affect the app you are building.

**Comment by rahulyaa** [comment]
@NikhilBansal21 Can you please follow the steps I posted above OR follow the GuestMeetingJoin demo?

**Comment by nabievnurlan7** [comment]
@rahulyaa =) 
Yes. This paths are correct
/home/lupus/AndroidStudioProjects/mobile-bank/libs 
/home/lupus/AndroidStudioProjects/mob-banking-skype2/mobile-bank/libs

I did everything as you said in my application. I made "libs" dir nearby "src" in "mobile-bank". Then i put to libs all *.aar files. 
Then in my gradle script i put     
    compile(name: "libucmp", ext: 'aar')
    compile(name: "platform", ext: 'aar')
    compile(name: "SkypeForBusiness", ext: 'aar')
    compile(name: "TelemetryService", ext: 'aar')
    compile(name: "ucmp-enums", ext: 'aar')
    compile(name: "TelemetryClient2", ext: 'aar')
    compile(name: "injector", ext: 'aar')
    compile(name: "android-database-sqlcipher", ext: 'aar')

I wrote flatdir settings in other gradle script. Application builded succesfully. 
But same Error! Crashes because "Cannot load native library"

In healthcare app's gradle file "compile(':annotations-1.0')" is apsent. Is it ok? Shoud i put annotations.jar into libs dir?

**Comment by NikhilBansal21** [comment]
@nabievnurlan7  can you tell me your annotation is taking 25 sdk number or 22??

**Comment by nabievnurlan7** [comment]
@NikhilBansal21 Excuse me =) But i didnt understand your question

**Comment by nabievnurlan7** [comment]
@rahulyaa I have another *.aar libs in projects. I inserted them into project with  Android Studio. 
Should put them into libs directory like Skype aap-files?

**Comment by NikhilBansal21** [comment]
@nabievnurlan7  is it showing this in gradle dependancy compile 'com.android.support:support-annotations:25.0.0' ???

**Comment by nabievnurlan7** [comment]
@NikhilBansal21  
compile 'com.android.support:support-v4:24.0.0'
compileSdkVersion 23

**Comment by rahulyaa** [comment]
@nabievnurlan7 yes Annotations.jar also needs to be put in the libs dir.

It is odd that the Healthcare sample works and your app does not not. I am running out of ideas on why your project does not pick up the binaries correctly. Does the GuestMeetingJoin demo work as well?

Right now, my only suggestion would be to create a simple Android Studio project, include the aar's and modify gradle flatdirs etc...
Simply call Application.getInstance(this); in your main activity directly from the SDK API rather than the sample. Dont copy / paste the files from the sample. See if that works.

**Comment by tharoldD** [comment]
@rahulyaa I had already tried the approach you have suggested to @nabievnurlan7 but even then, calling the...

`Application.getInstance(this);`

still results in a... "Could not load native library error"

**Comment by rahulyaa** [comment]
@tharoldD @nabievnurlan7 

What device are you trying this on? Which OS version does it have?

**Comment by tharoldD** [comment]
Huawei Mediapad M3, Android 6.0

**Comment by rahulyaa** [comment]
@tharoldD This should work. The sample is working on the device right?
If yes, 
Please share out on a file share:
1. Complete gradle console spew
2. logcat spew when you load the sample and hit the error.

**Comment by tharoldD** [comment]
I have been experimenting with a few different setups and it seems like the Skype SDK does not play well with [Realm](https://realm.io/docs/java/latest/).

At least in my case... starting from a new Android Studio project and adding the Skype SDK then tracing the application flow. I can confirm that the libraries are loaded.

Then on including Realm as the only dependency, and tracing the application flow, the app immediately fails to load native libraries.

@rahulyaa can you try to recreate this on your end, and confirm my findings. This could help point us in the right direction to solving this, I understand Realm packs it's own native libraries too.

@nabievnurlan7 are you using Realm or any other dependencies that have native libraries?

**Comment by NikhilBansal21** [comment]
@rahulyaa  still this problem is comming....i have tried to resolved it using offline gradle but as soon as i restart the project same error occurs...i would be really glad that you help me out with this it is giving alott of trouble to me on my project

**Comment by rahulyaa** [comment]
@NikhilBansal21 I am at a loss here. The best suggestion I have is to try a clean sample with the steps above and call application.getInstance and see if it works.

**Comment by techlectdinesh** [comment]
Hi @rahulyaa @nabievnurlan7 @NikhilBansal21 , could u please provide link to download libacomo.so file.
i am also stack on 

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.microsoft.office.sfb.sfbdemo/com.microsoft.office.sfb.sfbdemo.MainActivity}: java.lang.RuntimeException: Failed to load native library at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java)
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                   Caused by: java.lang.RuntimeException: Failed to load native library
                                                                                      at com.microsoft.office.sfb.appsdk.Application.LoadNativeLibrary(Application.java:129)
                                                                                      at com.microsoft.office.sfb.appsdk.Application.initialize(Application.java:71)
                                                                                      at com.microsoft.office.sfb.appsdk.Application.getInstance(Application.java:143)
                                                                                      at com.microsoft.office.sfb.sfbdemo.MainActivity.onCreate(MainActivity.java:63)
                                                                                      at android.app.Activity.performCreate(Activity.java:6237)
                                                                                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                      at android.app.ActivityThread.-wrap11(ActivityThread.java) 
                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by techlectdinesh** [comment]
Hello everyone final i have resolve this issue.
 Here is the problem in Application class - 

private static boolean LoadNativeLibrary() {
        try {
            if(!sLibComoIsLoaded.get()) {
                System.loadLibrary("gnustl_shared");
                System.loadLibrary("roottools");
                System.loadLibrary("RtmMediaManagerDyn");
                System.loadLibrary("acomo");
                sLibComoIsLoaded.set(true);
            }
        } catch (UnsatisfiedLinkError var2) {
            String strException = "Failed to load native library";
            throw new RuntimeException(strException);
        }

        return sLibComoIsLoaded.get();
    }

There is missing 

System.loadLibrary("sqlcipher");

**Comment by rahulyaa** [comment]
@techlectdinesh the sqlcipher is included in the package. Please look at this thread above. the aar needs to placed in the libs folder for this to work

**Comment by Jayanth-P** [comment]
Hello,
Is this issue resolved?
I too get this issue "java.lang.RuntimeException: Failed to load native library", when i try to get instance from Application i.e., "Application.getInstance(getActivity().getApplication().getApplicationContext());"
I have tried all the above steps but unfortunately none work for me.
Please Help!

**Comment by techlectdinesh** [comment]
Hi @Jayanth-P  ,

Please just add 

System.loadLibrary("sqlcipher");

 before below line.

this.application = Application.getInstance(this.getApplication().getApplicationContext());
 Happy Coding :)

**Comment by rahulyaa** [comment]
@Jayanth-P  @techlectdinesh 
You shouldn't need to load this explicitly. If you have placed all the SDK AAR's in the correct location as mentioned in my previous replies in this thread, the sqlcipher should get loaded automatically.

**Comment by alexcohn** [comment]
@rahulyaa In theory, on devices with Lollipop and above, the native lib dependencies are resolved automatically. There is some evidence, though, that Huawei ROM does not take care of this correctly.

**Comment by khurramengr** [comment]
@tharoldD same issue occurs when you add the ARCore dependency(**implementation 'com.google.ar:core:1.6.0'**) in build.gradle file.
Did you manage to find any fix in your case?
